title: "Minu blogi"
description: "minimaalne blogi kasutades markdowni"

remote_theme: pages-themes/minimal@v0.2.0
plugins:
  - jekyll-remote-theme

baseurl: "/aksel.ee"
url: "https://akseltalvoja.github.io"

markdown: kramdown
